from gym.envs.classic_control.cartpole import CartPoleEnv
from gym.envs.classic_control.mountain_car import MountainCarEnv
from gym.envs.classic_control.continuous_mountain_car import Continuous_MountainCarEnv
from gym.envs.classic_control.pendulum import PendulumEnv
from gym.envs.classic_control.acrobot import AcrobotEnv
from gym.envs.classic_control.cat_and_rat_environment import CatAndRatEnv
from gym.envs.classic_control.cat_and_rat_environment_fixed_rat import CatAndRatEnvFixedRat
from gym.envs.classic_control.cat_and_rat_environment_new_reward import CatAndRatEnvNewReward
